<a href="https://colab.research.google.com/github/vyhee/AI-Invasion2019/blob/master/IntroductionToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
hamoye = np.array([2, 3, 5, 7, 9, 11])

In [7]:
hamoye 

array([ 2,  3,  5,  7,  9, 11])

In [8]:
type(hamoye)

numpy.ndarray

In [9]:
hamoye [ :3]

array([2, 3, 5])

In [10]:
hamoye [ 3:]

array([ 7,  9, 11])

In [11]:
hamoye [ 2:4]

array([5, 7])

In [12]:
hamoye [ 3:5]

array([7, 9])

In [13]:
hamoye [5]

11

In [17]:
hamoye[4] = 26
print(hamoye)

[ 2  3  5  7 26 11]


In [21]:
import numpy as np
hamoye_2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]], float)
print(hamoye_2)

[[1. 3. 5. 7.]
 [2. 4. 6. 8.]]


In [22]:
hamoye_2[1,3]

8.0

In [23]:
hamoye_2[0,1]

3.0

In [24]:
hamoye_2[1,:]

array([2., 4., 6., 8.])

In [25]:
hamoye_2[:, 2]

array([5., 6.])

In [26]:
hamoye_2[-1:, -2:]

array([[6., 8.]])

In [28]:
hamoye_2.shape

(2, 4)

In [29]:
hamoye_2.dtype

dtype('float64')

In [31]:
len(hamoye_2)

2

In [32]:
14 in hamoye_2

False

In [33]:
2 in hamoye_2

True

In [34]:
hamoye_range = np.array(range(20), float)

In [35]:
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [36]:
hamoye_range = hamoye_range.reshape((4,5))

In [37]:
hamoye_range

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [41]:
hamoye_range = np.array(range(20), float).reshape(4,5)

In [42]:
hamoye_range

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [44]:
hamoye_range.transpose()

array([[ 0.,  5., 10., 15.],
       [ 1.,  6., 11., 16.],
       [ 2.,  7., 12., 17.],
       [ 3.,  8., 13., 18.],
       [ 4.,  9., 14., 19.]])

In [45]:
a = np.array([2,4,6,8], float)

In [47]:
a.tolist()

[2.0, 4.0, 6.0, 8.0]

In [48]:
list(a)

[2.0, 4.0, 6.0, 8.0]

In [49]:
a.fill(0)

In [50]:
a

array([0., 0., 0., 0.])

In [56]:
a = np.array([1,2,3], float)
b = np.array([4,5,6], float)
c = np.array([7,8,9], float)

print(a/c)
print(a*b)
print(b-c)
print(a+b+c)
np.concatenate((a,b,c))

[0.14285714 0.25       0.33333333]
[ 4. 10. 18.]
[-3. -3. -3.]
[12. 15. 18.]


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])